export enum RouterEnum {
  home = '',
  login = 'login',
  register = 'register',
  logout = 'logout',
  settings = 'settings',
  admin = 'admin',
  changePassword = 'change-password',
  deleteAccount = 'deleteAccount',
  forgetPassword = 'forget-password',
  preferences = 'preferences',
  fileDetails = 'file-details',
  notFound = 'not-found',
  karmelki = 'karmelki',
}
