version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bankapp
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres

  bankapp-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bankapp_api_container
    restart: always
    ports:
      - '3000:8080'
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: 'Host=postgres;Port=5432;Database=bankapp;Username=admin;Password=admin'

volumes:
  postgres_data:
